package shop.mtcoding.springblogriver._core.auth;

public enum JwtEnum {
    ACCESS_TOKEN_NOT_FOUND,
    ACCESS_TOKEN_INVALID,
    ACCESS_TOKEN_TIMEOUT,
    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_TIMEOUT,
    ACCESS_TOKEN_DONT_SAVED_REDIS,
    REFRESH_TOKEN_NOT_MATCH_SAVED_REDIS;
}
